os: linux
dist: focal
addons:
  apt:
    packages:
      - valgrind
      - doxygen
      - cppcheck
      - gcovr
      - git
      - cmake
      - clang
      - gcc
      - g++
      - cpplint

jobs:
  include:
    - name: "memory_checks"
      script:
        - ./scripts/checks.sh

    - name: "static_analyze"
      script:
        - ./scripts/static_analyze.sh

    - name: "linters"
      script:
        - ./kam1runetz/ci scripts/linters.sh

    - name: "unit_tests"
      script:
        - ./kam1runetz/ci scripts/tests.sh

    - name: "coverage"
      script:
        - ./kam1runetz/ci scripts/coverage.sh

notifications:
  email: false

branches:
  except:
    - master
