os: linux
dist: focal
addons:
  apt:
    packages:
    - valgrind
    - doxygen
    - cppcheck
    - gcovr
    - git
    - cmake
    - clang
    - gcc
    - g++
    - python3-pip
install:
- pip3 install cpplint
jobs:
  include:
  - name: memory_checks
    script: "./scripts/checks.sh"
  - name: static_analyze
    script: "./scripts/static_analyze.sh"
  - name: linters
    script: "./scripts/linters.sh"
  - name: unit_tests
    script: "./scripts/tests.sh"
  - name: coverage
    script: "./scripts/coverage.sh"

env:
  global:
    secure: ySaMV8E45/12S1pzaeDaVZ7EZLAVcbt06u629AkznF5y0TPF6YfDPYDNFozfhS6xozy5VEAixoPzFpsR3lpdpI0eW6TcZjLgAbMTzulhzhLS+aSDHVASW53Hm45KSsacMb0yUqWARRsWjSlMYAHwHmyl/IejC9v9BOiqdgUzzQZRIvD6eucJ1Vdup1CyPc9t143ZP+l6LHYgD0qP3zB10/MxqJe+99I8D9neIRQyWL/vswhmAKnUoiRz122c8XrEg6CBMOQMFOEE9pJAApGLW8MXYgvFKY/0wZT9lJWuIoNDQBBu5hCRpPWg+amuYKHl8tPPlSUusWNqac+iCf1LxVwDmL+LZkgQKMYID5H5gydgphkJHC776SGuAth1DfzhCrC1uUI1ip1Uw6TeywTZdW1O3tCyiFp8DaDOn1JtZXrznuU2DBP8DPr9pafzk+wHqmDxJhtsFHAFRuhoiTRMnRweG2TR7psA+wA16dP+GU1frGt7DoXBSnQE2NlSFn2MPwtRLHMbICilzlFHpq9iDjmfoR0hncITHPXhXIqNJKuJjjD7KEE3Kw3eHK8/Of/JzMpm8DW1Xl9NI0gl5gri0ww5SdU9vokrpYUPS1/bJl9143G+xdb2zuav4QfIGn0GUx+9HcErwbDobvChSstBrxuP2lY8ELBg4/kDqPY505M=

deploy:
  provider: releases
  user: Kam1runetzLabs
  file: static_analyze-report-src/*
  tag_name: "$TRAVIS_TAG"
  target_commitish: "$TRAVIS_COMMIT"
  name: "$TRAVIS_TAG"
  skip_cleanup: true
  overwrite: true
  on:
    branch: development

notifications:
  email: false

before_deploy:
- git config --local user.name "Kam1runetz"
- git config --local user.email "notsoserious2017@gmail.com"
- export TRAVIS_TAG="build-$TRAVIS_BUILD_NUMBER"
- echo "Tagging commit ${TRAVIS_COMMIT} with tag ${TRAVIS_TAG}"
- git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

branches:
  except:
  - master
