os: linux
dist: focal
addons:
  apt:
    packages:
    - valgrind
    - doxygen
    - cppcheck
    - gcovr
    - git
    - cmake
    - clang
    - gcc
    - g++
    - python3-pip
install:
- pip3 install cpplint
jobs:
  include:
  - stage: linters
    name: "Linter Processing"
    script: "./scripts/linters.sh"

    name: "Static Analizyng"
  - stage: static_analyze
    script: "./scripts/static_analyze.sh"

    name: "Memory Checks"
  - stage: memory_checks
    script: "./scripts/checks.sh"

    name: "Unit Tests"
  - stage: unit_tests
    script: "./scripts/tests.sh"

    name: "Coverage"
  - stage: coverage
    script: "./scripts/coverage.sh"

    deploy:
      provider: releases
      token: "$GITHUB_TOKEN "
      cleanup: false
      user: Kam1runetzLabs
      file: | 
       - "static-analyze-report-src/*"
       - "static-analyze-report-tests/*"
       - "coverage-report/*"
   tag_name: "$TRAVIS_TAG"
   target_commitish: "$TRAVIS_COMMIT"
   name: "$TRAVIS_TAG"
   overwrite: true
   on:
     branch: development

notifications:
  email: false

before_deploy:
  - git config --local user.name "Kam1runetz"
  - git config --local user.email "notsoserious2017@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
branches:
  except:
  - master
