os: linux
dist: focal
addons:
  apt:
    packages:
    - valgrind
    - doxygen
    - cppcheck
    - gcovr
    - git
    - cmake
    - clang
    - gcc
    - g++
    - python3-pip
install:
- pip3 install cpplint
jobs:
  include:
  - name: memory_checks
    script: "./scripts/checks.sh"
  - name: static_analyze
    script: "./scripts/static_analyze.sh"
  - name: linters
    script: "./scripts/linters.sh"
  - name: unit_tests
    script: "./scripts/tests.sh"
  - name: coverage
    script: "./scripts/coverage.sh"


deploy:
   provider: releases
   github_token: "$GITHUB_TOKEN"
   skip_cleanup: true
   user: Kam1runetzLabs
   file: | 
    static-analyze-report-src/*
    static-analyze-report-tests/*
    coverage-report/*
   tag_name: "$TRAVIS_TAG"
   target_commitish: "$TRAVIS_COMMIT"
   name: "$TRAVIS_TAG"
   overwrite: true
   on:
     branch: development

notifications:
  email: false

before_deploy:
- git config --local user.name "Kam1runetz"
- git config --local user.email "notsoserious2017@gmail.com"
- export TRAVIS_TAG="build-$TRAVIS_BUILD_NUMBER"
- echo "Tagging commit ${TRAVIS_COMMIT} with tag ${TRAVIS_TAG}"
- git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

branches:
  except:
  - master
