name: CCI
os: linux
dist: focal
addons:
  apt:
    packages:
    - valgrind
    - doxygen
    - cppcheck
    - gcovr
    - git
    - cmake
    - clang
    - gcc
    - g++
    - python3-pip
install:
  - pip3 install cpplint
jobs:
  include:
  - name: memory_checks
    script:
    - "./scripts/checks.sh"
  - name: static_analyze
    script:
    - "./scripts/static_analyze.sh"
  - name: linters
    script:
    - "./scripts/linters.sh"
  - name: unit_tests
    script:
    - "./scripts/tests.sh"
  - name: coverage
    script:
    - "./scripts/coverage.sh"
branches:
  except:
  - master
